version: "3.9"
services:
  backend:
    build: ./backend
    networks:
      - my-network
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    networks:
      - my-network
    ports:
      - "4173:80"
    env_file:
      - ./frontend/.env

networks:
  my-network:
    driver: bridge
